import React, { useEffect, useRef, useState } from 'react';

let mermaidInitialized = false;

/**
 * Sanitize Mermaid code to fix common syntax issues generated by LLMs.
 * Mermaid breaks on unquoted labels containing apostrophes, question marks,
 * parentheses, or other special characters. This wraps them in double quotes.
 */
function sanitizeMermaid(code: string): string {
  let sanitized = code;

  // First pass: escape problematic characters inside already-quoted bracket labels
  // A["text with [0;3] inside"] → A["text with &#91;0&#59;3&#93; inside"]
  sanitized = sanitized.replace(
    /(\w+)\["([^"]*?)"\]/g,
    (_match, id, label) => {
      const escaped = label
        .replace(/\[/g, '&#91;')
        .replace(/\]/g, '&#93;')
        .replace(/;/g, '&#59;');
      return `${id}["${escaped}"]`;
    }
  );

  // Same for already-quoted curly-brace labels: B{"text"}
  sanitized = sanitized.replace(
    /(\w+)\{"([^"]*?)"\}/g,
    (_match, id, label) => {
      const escaped = label
        .replace(/\{/g, '&#123;')
        .replace(/\}/g, '&#125;')
        .replace(/;/g, '&#59;');
      return `${id}{"${escaped}"}`;
    }
  );

  // Same for already-quoted round-bracket labels: C("text")
  sanitized = sanitized.replace(
    /(\w+)\("([^"]*?)"\)/g,
    (_match, id, label) => {
      const escaped = label
        .replace(/\(/g, '&#40;')
        .replace(/\)/g, '&#41;')
        .replace(/;/g, '&#59;');
      return `${id}("${escaped}")`;
    }
  );

  // Wrap unquoted square-bracket labels containing special chars in double quotes
  // A[L'élève observe] → A["L'élève observe"]
  // Skip already-quoted labels (handled above)
  sanitized = sanitized.replace(
    /(\w+)\[([^\]"]+)\]/g,
    (_match, id, label) => {
      if (/['"?!(){};<>&≥≤]/.test(label) || /[\u00C0-\u024F]/.test(label)) {
        return `${id}["${label}"]`;
      }
      return _match;
    }
  );

  // Wrap curly-brace (decision) labels containing special chars in double quotes
  // B{Est-il prêt ?} → B{"Est-il prêt ?"}
  sanitized = sanitized.replace(
    /(\w+)\{([^}"]+)\}/g,
    (_match, id, label) => {
      if (/['"?!();<>&≥≤]/.test(label) || /[\u00C0-\u024F]/.test(label)) {
        return `${id}{"${label}"}`;
      }
      return _match;
    }
  );

  // Wrap round-bracket labels (for stadium-shaped nodes) the same way
  sanitized = sanitized.replace(
    /(\w+)\(([^)"]+)\)/g,
    (_match, id, label) => {
      if (/['"?!{}[\];<>&≥≤]/.test(label) || /[\u00C0-\u024F]/.test(label)) {
        return `${id}("${label}")`;
      }
      return _match;
    }
  );

  // Replace mathematical comparison symbols that Mermaid can't handle
  sanitized = sanitized.replace(/≥/g, '>=');
  sanitized = sanitized.replace(/≤/g, '<=');

  return sanitized;
}

const MermaidBlock: React.FC<{ chart: string }> = ({ chart }) => {
  const containerRef = useRef<HTMLDivElement>(null);
  const [svg, setSvg] = useState<string>('');
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    let cancelled = false;

    const renderChart = async () => {
      try {
        const mermaid = (await import('mermaid')).default;

        if (!mermaidInitialized) {
          const isDark = document.documentElement.classList.contains('dark');
          mermaid.initialize({
            startOnLoad: false,
            theme: isDark ? 'dark' : 'default',
            securityLevel: 'strict',
          });
          mermaidInitialized = true;
        }

        const id = `mermaid-${crypto.randomUUID().replace(/-/g, '')}`;
        const sanitized = sanitizeMermaid(chart);
        const { svg: renderedSvg } = await mermaid.render(id, sanitized);

        if (!cancelled) {
          setSvg(renderedSvg);
          setLoading(false);
        }
      } catch (err) {
        // If sanitized version failed, try a more aggressive cleanup
        try {
          const aggressiveClean = sanitizeMermaid(chart)
            .replace(/[?!]/g, '')
            .replace(/['']/g, "'")
            .replace(/[""]/g, '"');
          const retryId = `mermaid-${crypto.randomUUID().replace(/-/g, '')}`;
          const { svg: retrySvg } = await mermaid.render(retryId, aggressiveClean);
          if (!cancelled) {
            setSvg(retrySvg);
            setLoading(false);
          }
        } catch {
          if (!cancelled) {
            setError(err instanceof Error ? err.message : 'Erreur de rendu du diagramme');
            setLoading(false);
          }
        }
      }
    };

    renderChart();

    return () => {
      cancelled = true;
    };
  }, [chart]);

  if (loading) {
    return (
      <div className="flex items-center justify-center py-8 text-gray-400">
        <svg className="animate-spin h-5 w-5 mr-2" viewBox="0 0 24 24">
          <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" fill="none" />
          <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
        </svg>
        Chargement du diagramme…
      </div>
    );
  }

  if (error) {
    return (
      <pre className="bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-xl p-4 text-sm text-red-700 dark:text-red-300 overflow-x-auto my-4">
        <div className="text-xs font-semibold mb-2 text-red-500">Diagramme invalide</div>
        {chart}
      </pre>
    );
  }

  return (
    <div
      ref={containerRef}
      data-mermaid
      className="my-4 flex justify-center overflow-x-auto"
      dangerouslySetInnerHTML={{ __html: svg }}
    />
  );
};

export default MermaidBlock;
